version: "3.6"

services:
  db:
    volumes:
      - db-data:/pg/11/data
    ports:
      - 5432
    environment:
      - PGDATA=/pg/11/data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.labels.type == db

volumes:
  db-data: