version: "3.6"

services:

  db:
    image: ${DOCKER_REGISTRY}/postgres:11.5

  audit-service:
    image: ${DOCKER_REGISTRY}/audit/audit-service:${TAG}

  audit-webapp:
    image: ${DOCKER_REGISTRY}/audit/audit-webapp:${TAG}
