version: "3.6"

services:

  audit-service:
    build:
      context: audit-service
      args:
        JAR_FILE: target/audit-service.jar

  audit-web:
    build:
      context: audit-web
      args:
        JAR_FILE: target/audit-web.jar
