version: '3.6'

services:

  activemq:
    image: "rmohr/activemq:5.15.9"
    ports:
      - 61616
      - 8161
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        max_attempts: 3