version: '3.6'

services:

  postgres:
    image: postgres:11.4-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=audit
    networks:
      - audit

  audit-service:
    environment:
      AUDIT_BACKEND_URL: http://audit-service:8080
    build:
      context: audit-service
      args:
        JAR_FILE: target/audit-service.jar
    networks:
      - audit

  audit-ui:
    ports:
      - 8083:8083
    build:
      context: audit-ui
      args:
        JAR_FILE: target/audit-ui.jar
    networks:
      - audit

networks:
  audit:
