version: "3.6"

services:

  postgresql:
    image: ${DOCKER_REGISTRY}/audit/db/develop:${TAG:-latest}

  audit-service:
    image: ${DOCKER_REGISTRY}/audit/audit-service:${TAG:-latest}

  audit-web:
    image: ${DOCKER_REGISTRY}/audit/audit-web:${TAG:-latest}
