version: "3.6"

services:

  audit-service:
    build:
      context: .
      args:
        JAR_FILE: audit-service/target/audit-service.jar

  audit-webapp:
    build:
      context: .
      args:
        JAR_FILE: audit-webapp/target/audit-webapp.jar
