version: '3.6'

services:

  postgres:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=audit

  audit-service:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/audit

  audit-web:
    environment:
      - AUDIT_BACKEND_URL=http://audit-service:8082/api
