version: "3.6"

services:

  audit-service:
    image: 538721144237.dkr.ecr.eu-west-1.amazonaws.com/audit-service:${TAG:-latest}

  audit-ui:
    image: 538721144237.dkr.ecr.eu-west-1.amazonaws.com/audit-ui:${TAG:-latest}
