version: "3.6"

services:

  db:
    image: ${DOCKER_REGISTRY}/audit/db:${TAG}

  audit-service:
    image: ${DOCKER_REGISTRY}/audit/audit-service:${TAG:-latest}

  audit-webapp:
    image: ${DOCKER_REGISTRY}/audit/audit-webapp:${TAG:-latest}
