version: '3.6'

services:

  audit-service:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/audit
      JAVA_OPTS: -Xmx200m
      LOGGING_LEVEL_ROOT: ERROR
    ports:
      - 8080
    deploy:
      resources:
        limits:
          memory: 700M
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
          - node.labels.dc == hetzner
    healthcheck:
      test: curl -f http://localhost:8080/monitoring/health | grep -io '^{"status":"UP"' || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 300s
    depends_on:
      - db

  audit-webapp:
    environment:
      SPRING_CLOUD_CONSUL_CONFIG_PREFIX: audit
      AUDIT_BACKEND_URL: http://audit-service:8080/api
      AUDIT_EXPORT_URL: ${audit_export_url}
      JAVA_OPTS: -Xmx300m
      LOGGING_LEVEL_ROOT: ERROR
    ports:
      - 8080
    deploy:
      resources:
        limits:
          memory: 800M
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
          - node.labels.dc == hetzner
    healthcheck:
      test: curl -f http://localhost:8080/monitoring/health | grep -io '^{"status":"UP"' || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 300s