version: "3.6"

services:
  db:
    volumes:
      - audit-db-data:/pg/12/data
    ports:
      - 5432
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.labels.type == db

volumes:
  audit-db-data: