version: "3.6"

services:

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgresql

  audit-service:
    build:
      context: .
      args:
        JAR_FILE: audit-service/target/audit-service.jar

  audit-web:
    build:
      context: .
      args:
        JAR_FILE: audit-web/target/audit-web.jar
