version: '3.6'

services:

  db:
    image: ${DOCKER_REGISTRY}/audit/db/develop
    ports:
      - "5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: audit
    deploy:
      resources:
        limits:
          memory: 1024M
      placement:
        constraints:
          - node.labels.type == db
#    command: postgres -c shared_preload_libraries='pg_pathman'

  audit-service:
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/audit
      JAVA_OPTS: -Xmx200m
    ports:
      - 8080
    deploy:
      resources:
        limits:
          memory: 700M
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
          - node.labels.dc == hetzner
    healthcheck:
      test: curl -f http://localhost:8080/monitoring/health | grep -io '^{"status":"UP"' || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 300s
#    depends_on:
#      - postgres

  audit-web:
    environment:
      AUDIT_BACKEND_URL: "http://audit-service:8080/api"
      JAVA_OPTS: -Xmx300m
    ports:
      - 8080
    deploy:
      resources:
        limits:
          memory: 800M
      restart_policy:
        max_attempts: 3
      placement:
        constraints:
          - node.labels.dc == hetzner
    healthcheck:
      test: curl -f http://localhost:8080/monitoring/health | grep -io '^{"status":"UP"' || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 300s
#    depends_on:
#      - audit-service
