Модуль "Аудит" (или Подсистема журналирования) предназначен для журналирования :

* Действий пользователей
* Интеграционных сервисов
* Авторизации и сессий, а также неудачных попыток доступа

== Локальный запуск модуля в докере
* Если были изменения в модулях audit-api, audit-web
----
mvn -pl audit-api,audit-web clean install
----
* Для формирования jar файлов в модулях audit-service, audit-webapp
----
mvn -pl audit-service,audit-webapp clean package
----
* Для создания образов и запуска контейнеров необходимо запустить плагин docker-compose:up в модуле audit-webapp
----
mvn -pl audit-webapp docker-compose:up -P docker-dev
----
* Для остановки и удаления контейнеров нужно прогнать плагин docker-compose:down в модуле audit-webapp
----
mvn -pl audit-webapp docker-compose:down -P docker-dev
----
* Для удаления созданных образов можно выполнить в консоли
----
docker rmi audit_db audit_audit-service audit_audit-webapp
----
После выполнения docker-compose:up будет поднято три контейнера: +
audit_db_1 контейнер с бд, подключение к постгресу доступно по порту 8952 +
audit_audit-service_1 контейнер с бэкендом, доступен по порту 8951 +
audit_audit-webapp_1 контейнер с вебприложением, доступен по порту 8950


== Настройки запуска сервиса для получения логов событий Keycloak по расписанию
Предварительно в Keycloak необходимо включить логирование событий.

.Для работы сервиса следует добавить следующие настройки в properties:
* URL где расположен сервис бэкенда
----
audit.service.url
----
* Базовый адрес сервиса аутентификации(например http://localhost:8080/auth/realms/master/protocol/openid-connect)
----
audit.security.oauth2.auth-server-uri=
----
* Адрес сервиса получения токена аутентификации(например /token)
----
audit.security.oauth2.access-token-uri=
----
* Идентификатор клиента OAuth2 OpenId Connect
----
audit.security.oauth2.client-id=
----
* Секретный ключ клиента OAuth2 OpenId Connect
----
audit.security.oauth2.client-secret=
----
* Адрес до realm, с которого будет происходить получение логов событий (например http://localhost:8080/auth/admin/realms/master)
----
audit.security.oauth2.events-url=
----
* Код подсистемы, которая будет сохраняться в аудит(например security)
----
audit.security.oauth2.code=
----
* Крон выражение расписания получения логов событий из OAuth2 (если не указана или указано "-", то сервис не будет запущен)
----
audit.security.oauth2.events-schedule=
----

== Сервис экспорта журналов audit-export в зависимости у audit-service
Выгружает записи с соответствующими полями для каждого из журналов, согласно примененной фильтрации.
Действуют такие же ограничения по периоду выборки, т.е. 31 день.
Выгрузка происходит в csv формате.


Настройки
Доступность по адресу задается переменной
audit.export.url = #example http://localhost:8951/api

Доступны для переопределения некоторые настройки
# Замена null начений на заданное
export.config.if-null-value = #default null
# Формат даты для поля даты события
export.config.date-format = #default dd.MM.yyyy HH:mm:ss
# Имя файла, формируемого при выгрузке
export.config.file-name = #default audit_export

# Принудительный лимит при получении строк журналов, 0 для игнорирования настройки
export.query.limit-select-row = #default 0
# Возможно требует уточнение на сервере, в зависимости от ресурсов
export.query.hint-fetch-size = #default 10
# Разделитель значений
export.csv.field-delimiter =  #default ,
# Признак вывода в файл заголовкой полей
export.csv.print-field-name = #default true