#FROM 538721144237.dkr.ecr.eu-west-1.amazonaws.com/postgres:11.5
FROM 538721144237.dkr.ecr.eu-west-1.amazonaws.com/audit/db/develop

COPY docker-entrypoint-initdb.d /docker-entrypoint-initdb.d

EXPOSE 5432